[TEMP] treewide: remove roundedwindow feature
error:
In file included from kwin-plugins/obj-x86_64-linux-gnu/plugins/roundedwindow/roundedwindow_autogen/EWIEGA46WW/moc_roundedwindow.cpp:10,
                 from kwin-plugins/obj-x86_64-linux-gnu/plugins/roundedwindow/roundedwindow_autogen/mocs_compilation.cpp:2:
kwin-plugins/obj-x86_64-linux-gnu/plugins/roundedwindow/roundedwindow_autogen/EWIEGA46WW/../../../../../plugins/roundedwindow/roundedwindow.h:36:36: error: ‘LanczosCacheRole’ is not a member of ‘KWin::DataRole’
   36 |         BaseRole = KWin::DataRole::LanczosCacheRole + 100,
      |

the error might be caused due to `kwineffects.h` and in plugins/roundedwindow/roundedwindow.h:36 and plugins/roundedwindow/roundedwindow.cpp:273, Lanczous filter was used. However it was recently removed in `kwineffects.h`.

Signed-off-by: UsiFX <xprjkts@gmail.com>